### ISSUE TITLE
Создать hello world приложение для фронта

### ISSUE THREAD

**Issue by dancecoder** [dancecoder/chain-book#1]
Для фонта будем использовать стандартную связку react+reduce.
Требуется в папке frontend этого репозитория сгенерировать фронтовое приложение при помощи стандартного cli.

**Comment by sanchine** [comment]
Номер задачи 1. Hello world приложение (файлы добавлены в папку frontend). 
Первый делом необходимо было подключение библиотеки для javascript - React.js, которое имеет множество полезных для работы инструментов и в связке с Redux, доп. библиотекой для React, мы сможем менять данные на странице и её адрес лишь изменяя значения в javascript, а не переходя на отдельную страницу по ссылке.

Выполнив эту задачу, мы подготовили фундамент для комфортной разработки приложения.
